steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/whatsapp-service', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/whatsapp-service']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'whatsapp-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/whatsapp-service'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '1'
      - '--port'
      - '3001'
      - '--set-env-vars'
      - 'GCS_BUCKET_NAME=bloodbank-whatsapp-sessions,NODE_ENV=production'

images:
  - 'gcr.io/$PROJECT_ID/whatsapp-service'

options:
  logging: CLOUD_LOGGING_ONLY
